apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-3g11
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-3g11
    app.kubernetes.io/part-of: tkrw-pr714-0075-0067-app
  name: devfile-sample-3g11
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-3g11
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-3g11
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0067-tenant/tkrw-pr714-0075-0067-app/devfile-sample-3g11@sha256:0a3777e55ce43a10d7f8d08403a47dfa39d9dce638d57c5613b670121036a046
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
